-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admin
(
    id serial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT admin_pkey PRIMARY KEY (id),
    CONSTRAINT admin_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.berita_artikel
(
    id serial NOT NULL,
    judul character varying(255) COLLATE pg_catalog."default" NOT NULL,
    isi_berita text COLLATE pg_catalog."default" NOT NULL,
    gambar_berita character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    kategori_id integer,
    CONSTRAINT berita_artikel_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.daftar_proyek
(
    id serial NOT NULL,
    judul character varying(255) COLLATE pg_catalog."default" NOT NULL,
    isi_proyek text COLLATE pg_catalog."default" NOT NULL,
    gambar_proyek character varying(255) COLLATE pg_catalog."default" NOT NULL,
    kategori_id integer,
    tahun character varying(20) COLLATE pg_catalog."default",
    nama_tim character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT daftar_proyek_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.deskripsi
(
    id serial NOT NULL,
    isi_deskripsi text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT deskripsi_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dosen_multimedia
(
    id integer NOT NULL DEFAULT nextval('tim_kreatif_id_seq'::regclass),
    nama character varying(255) COLLATE pg_catalog."default" NOT NULL,
    jabatan character varying(255) COLLATE pg_catalog."default" NOT NULL,
    gambar_tim character varying(255) COLLATE pg_catalog."default" NOT NULL,
    link_linkedin text COLLATE pg_catalog."default",
    link_instagram text COLLATE pg_catalog."default",
    link_github text COLLATE pg_catalog."default",
    nidn character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT tim_kreatif_pkey PRIMARY KEY (id),
    CONSTRAINT dosen_multimedia_nidn_key UNIQUE (nidn)
);

CREATE TABLE IF NOT EXISTS public.galeri
(
    id serial NOT NULL,
    deskripsi text COLLATE pg_catalog."default" NOT NULL,
    gambar_galeri character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT galeri_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.kategori
(
    id serial NOT NULL,
    nama_kategori character varying(100) COLLATE pg_catalog."default" NOT NULL,
    jenis character varying(20) COLLATE pg_catalog."default" DEFAULT 'proyek'::character varying,
    CONSTRAINT kategori_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.mahasiswa
(
    id serial NOT NULL,
    nim character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nama character varying(66) COLLATE pg_catalog."default" NOT NULL,
    prodi_id integer NOT NULL,
    CONSTRAINT mahasiswa_pkey PRIMARY KEY (id),
    CONSTRAINT mahasiswa_nim_key UNIQUE (nim)
);

CREATE TABLE IF NOT EXISTS public.mahasiswa_proyek
(
    id serial NOT NULL,
    mahasiswa_id integer NOT NULL,
    proyek_id integer NOT NULL,
    CONSTRAINT mahasiswa_proyek_pkey PRIMARY KEY (id),
    CONSTRAINT uniq_mahasiswa_proyek UNIQUE (mahasiswa_id, proyek_id)
);

CREATE TABLE IF NOT EXISTS public.misi
(
    id serial NOT NULL,
    judul character varying(255) COLLATE pg_catalog."default" NOT NULL,
    isi_misi text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT misi_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.nilai
(
    id serial NOT NULL,
    judul character varying(255) COLLATE pg_catalog."default" NOT NULL,
    gambar_nilai character varying(255) COLLATE pg_catalog."default" NOT NULL,
    deskripsi text COLLATE pg_catalog."default",
    CONSTRAINT nilai_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.partner
(
    id serial NOT NULL,
    nama_brand character varying(255) COLLATE pg_catalog."default" NOT NULL,
    gambar_brand character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT partner_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pengunjung
(
    id serial NOT NULL,
    ip_address character varying(50) COLLATE pg_catalog."default" NOT NULL,
    tanggal date NOT NULL DEFAULT CURRENT_DATE,
    waktu timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pengunjung_pkey PRIMARY KEY (id),
    CONSTRAINT unique_visit_per_day UNIQUE (ip_address, tanggal)
);

CREATE TABLE IF NOT EXISTS public.prodi
(
    id serial NOT NULL,
    nama_prodi character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT prodi_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sejarah
(
    id serial NOT NULL,
    judul character varying(255) COLLATE pg_catalog."default" NOT NULL,
    isi text COLLATE pg_catalog."default" NOT NULL,
    tahun character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT sejarah_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.struktur_organisasi
(
    id serial NOT NULL,
    gambar_organisasi character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT struktur_organisasi_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.visi
(
    id serial NOT NULL,
    judul character varying(255) COLLATE pg_catalog."default" NOT NULL,
    isi_visi text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT visi_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.berita_artikel
    ADD CONSTRAINT berita_artikel_kategori_id_fkey FOREIGN KEY (kategori_id)
    REFERENCES public.kategori (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.daftar_proyek
    ADD CONSTRAINT daftar_proyek_kategori_id_fkey FOREIGN KEY (kategori_id)
    REFERENCES public.kategori (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.mahasiswa
    ADD CONSTRAINT mahasiswa_prodi_id_fkey FOREIGN KEY (prodi_id)
    REFERENCES public.prodi (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.mahasiswa_proyek
    ADD CONSTRAINT mahasiswa_proyek_mahasiswa_id_fkey FOREIGN KEY (mahasiswa_id)
    REFERENCES public.mahasiswa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.mahasiswa_proyek
    ADD CONSTRAINT mahasiswa_proyek_proyek_id_fkey FOREIGN KEY (proyek_id)
    REFERENCES public.daftar_proyek (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;